controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# MenuController


app_accueil:
    path: /
    controller : App\Controller\MenuController::index


app_categorie:
    path: /categorie 
    controller : App\Controller\MenuController::categorie

app_plat :
    path: /plat 
    controller : App\Controller\MenuController::plat

app_plat_cat :
    path : /plats/{libelle}
    controller : App\Controller\MenuController::plat_cat


# ContactController


app_contact : 
    path : /contact 
    controller : App\Controller\ContactController::mail


# SecurityController


app_login : 
    path : /login
    controller : App\Controller\SecurityController::login




# RegistrationController


app_register :
    path : /inscription
    controller : App\Controller\RegistrationController::register


# ProfileController


app_profile :
    path : /profile
    controller : App\Controller\ProfileController::index

app_detail_profile :
    path : /detail
    controller : App\Controller\ProfileController::profile
